version: 0.2

phases:
 pre_build:
  commands:
   - echo Logging in to Amazon ECR...
   - aws --version
   - REPOSITORY_URI=719472067992.dkr.ecr.us-west-1.amazonaws.com/neurosales
   - IMAGE_TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)"
 build:
  commands:
   - echo Build started on `date`
   - echo Building the docker images.... 
   - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
 post_build:
  commands:
   - echo Build completed on `date`
   - echo Pushing the docker images...
   - $(aws ecr get-login --no-include-email --region us-west-1)
   - docker push "$REPOSITORY_URI:$IMAGE_TAG"
   - echo Writing image definitions file...
   - printf '{"Image":"%s:%s"}' $REPOSITORY_URI $IMAGE_TAG > imagedefinitions.json
   - cat imagedefinitions.json
artifacts:
 files: 
  - imagedefinitions.json
  - service.yml
  - production.json
 discard-paths: yes
