---
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation for creating ECS services..
Parameters:
  Cluster:
    Type: String
  DesiredCount:
    Type: Number
  Image:
    Type: String
  ContainerNameServer:
    Type: String
  ContainerNameNode:
    Type: String
  Role:
    Type: String
  TargetGroupArnServer:
    Type: String
  TargetGroupArnNode:
    Type: String
Resources:
  ServiceServer:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Ref: Cluster
      TaskDefinition:
        Ref: TaskDefinitionServer
      Role:
        Ref: Role
      LoadBalancers:
      - ContainerName:
          Ref: ContainerNameServer
        ContainerPort: '8080'
        TargetGroupArn:
          Ref: TargetGroupArnServer
      DesiredCount:
        Ref: DesiredCount
  TaskDefinitionServer:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: Service
      ContainerDefinitions:
      - Name:
          Ref: ContainerNameServer
        Image:
          Ref: Image
        Memory: 512
        Essential: true
        PortMappings:
        - Protocol: tcp
          ContainerPort: 8080
          HostPort: 8080
  ServiceNode:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Ref: Cluster
      TaskDefinition:
        Ref: TaskDefinitionNode
      Role:
        Ref: Role
      LoadBalancers:
      - ContainerName:
          Ref: ContainerNameNode
        ContainerPort: '3000'
        TargetGroupArn:
          Ref: TargetGroupArnNode
      DesiredCount:
        Ref: DesiredCount
  TaskDefinitionNode:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: Service
      ContainerDefinitions:
      - Name:
          Ref: ContainerNameNode
        Image:
          Ref: Image
        Memory: 512
        Essential: true
        PortMappings:
        - Protocol: tcp
          ContainerPort: 3000
          HostPort: 3000

