---
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation for creating ECS services..
Parameters:
  Cluster:
    Type: String
  DesiredCount:
    Type: Number
  ImageNode:
    Type: String
  ImageServer:
    Type: String
  ContainerNameServer:
    Type: String
  ContainerNameNode:
    Type: String
  Role:
    Type: String
  TargetGroupArnServer:
    Type: String
  TargetGroupArnNode:
    Type: String
Resources:
  ServiceServer:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Ref: Cluster
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 10
      TaskDefinition:
        Ref: TaskDefinitionServer
      Role:
        Ref: Role
      LoadBalancers:
      - ContainerName:
          Ref: ContainerNameServer
        ContainerPort: '8080'
        TargetGroupArn:
          Ref: TargetGroupArnServer
      DesiredCount:
        Ref: DesiredCount
  TaskDefinitionServer:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: Service
      ContainerDefinitions:
      - Name:
          Ref: ContainerNameServer
        Image:
          Ref: ImageServer
        Memory: 2048
        Cpu: 1024
        Essential: true
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: awslogs-server
            awslogs-region: us-west-1
            awslogs-stream-prefix: tomcat
        PortMappings:
        - Protocol: tcp
          ContainerPort: 8080
          HostPort: 8080
  ServiceNode:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Ref: Cluster
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 10
      TaskDefinition:
        Ref: TaskDefinitionNode
      Role:
        Ref: Role
      LoadBalancers:
      - ContainerName:
          Ref: ContainerNameNode
        ContainerPort: '3000'
        TargetGroupArn:
          Ref: TargetGroupArnNode
      DesiredCount:
        Ref: DesiredCount
  TaskDefinitionNode:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: Service
      ContainerDefinitions:
      - Name:
          Ref: ContainerNameNode
        Image:
          Ref: ImageNode
        Memory: 512
        Essential: true
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: awslogs-Node
            awslogs-region: us-west-1
            awslogs-stream-prefix: RBAUI
        PortMappings:
        - Protocol: tcp
          ContainerPort: 3000
          HostPort: 3000

